### ISSUE TITLE
Cucumberator works bad with absolute paths

### ISSUE THREAD

**Issue by MartynasM** [vidmantas/cucumberator#2]
<code>cucumber /home/bugo/workspace/features/calendar/balance_transfer.feature</code>

After typing in any step: 
<code>#\<Errno::ENOENT: No such file or directory - /home/bugo/workspace/home/bugo/workspace/features/calendar/balance_transfer.feature></code>

Kindly revert.

**Comment by rbviz** [comment]
Why is this still open?
